version: 2

sources:
  - name: COVID19_Epidemiological_Data
    description: 'That is a test.'
    database: COVID19_Epidemiological_Data
    schema: PUBLIC
    tables:
      - name: DEMOGRAPHICS
        description: 'That is another test.'